// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;

namespace Network
{

    public class Alement
    {
        public object from;
        public object to;
        public float distance;
        public int duration;
    }


    public class Result2
    {
        public Alement[] elements;
    }


    public class NDistance
    {

        public string status;

        public string message;

        public Result2 result;
    }
}