// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System.Collections.Generic;

namespace Network
{
    public class NItem
    {
        public int id;
        
        public int type;
        
        public int pprice;
        
        public int cnt;
        
        public int nprice;
    };
}

