// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;

namespace Network
{

    public class Adress
    {
        public string city;
        public string district;
        public string province;
        public string street;
        public string street_number;
    }


    public class Result
    {
        public object location;
        public string formatted_address;
        public string business;
        public Adress addressComponent;
        public int cityCode;
    }


    public class Row
    {
        public string status;
        public Result location;
    }


    public class NLocation
    {

        public string resultcode;

        public string resultinfo;

        public Row row;
    }
}