// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;

namespace Network
{

    public class Address
    {
        public string nation;
        public string province;
        public string city;
        public string district;
        public string street;
        public string street_number;
    }


    public class Result
    {
        public object location;
        public string address;
        public object formatted_address;
        public Address address_component;
        public object ad_info;
        public object address_reference;
    }


    public class NLocation
    {

        public string status;

        public string message;

        public Result result;
    }
}