// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;

namespace Network
{
    public class NUser
    {
        public string name;
        
        public int paymode;
        
        public Int64 tel;
        
        public string addr;
        
        public int balance;

        public int type;

        public int bases;
    
    }
}
