//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Config
{
    using System;
    
    
    public struct TBases
    {
        
        // 分店编码
        public int id;
        
        // 分点名
        public string name;
        
        // 城市
        public string city;
        
        // 区域
        public string district;
        
        // 纬度
        public float lat;
        
        // 经度
        public float lng;
    }
}
